# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectmainfile = QtWidgets.QToolButton(self.centralwidget)
        self.selectmainfile.setGeometry(QtCore.QRect(440, 90, 41, 21))
        self.selectmainfile.setObjectName("selectmainfile")
        self.selectmainfile_label = QtWidgets.QLabel(self.centralwidget)
        self.selectmainfile_label.setGeometry(QtCore.QRect(210, 70, 211, 16))
        self.selectmainfile_label.setObjectName("selectmainfile_label")
        self.selectsonfile_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.selectsonfile_listWidget.setGeometry(QtCore.QRect(210, 180, 221, 321))
        self.selectsonfile_listWidget.setObjectName("selectsonfile_listWidget")
        self.selectson_label = QtWidgets.QLabel(self.centralwidget)
        self.selectson_label.setGeometry(QtCore.QRect(210, 160, 171, 16))
        self.selectson_label.setObjectName("selectson_label")
        self.selectsonfile = QtWidgets.QToolButton(self.centralwidget)
        self.selectsonfile.setGeometry(QtCore.QRect(440, 180, 41, 21))
        self.selectsonfile.setObjectName("selectsonfile")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 161, 471))
        font = QtGui.QFont()
        font.setFamily("Abril Fatface")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.mainfile_showurl = QtWidgets.QComboBox(self.centralwidget)
        self.mainfile_showurl.setGeometry(QtCore.QRect(210, 90, 221, 22))
        self.mainfile_showurl.setObjectName("mainfile_showurl")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_textBrowser.setGeometry(QtCore.QRect(550, 180, 211, 331))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(550, 160, 41, 16))
        self.log_label.setObjectName("log_label")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(440, 210, 75, 23))
        self.delButton.setObjectName("delButton")
        self.filemod = QtWidgets.QPushButton(self.centralwidget)
        self.filemod.setGeometry(QtCore.QRect(550, 110, 75, 23))
        self.filemod.setObjectName("filemod")
        self.dirmod = QtWidgets.QPushButton(self.centralwidget)
        self.dirmod.setGeometry(QtCore.QRect(650, 110, 75, 23))
        self.dirmod.setObjectName("dirmod")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 80, 171, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件批量处理"))
        self.selectmainfile.setText(_translate("MainWindow", "..."))
        self.selectmainfile_label.setText(_translate("MainWindow", "选择主文件夹-要复制的文件夹"))
        self.selectson_label.setText(_translate("MainWindow", "选择被修改的文件夹-可多选"))
        self.selectsonfile.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "启动！"))
        self.log_label.setText(_translate("MainWindow", "日志"))
        self.delButton.setText(_translate("MainWindow", "删除"))
        self.filemod.setText(_translate("MainWindow", "复制文件"))
        self.dirmod.setText(_translate("MainWindow", "复制目录"))
        self.label.setText(_translate("MainWindow", "选择模式-默认是目录"))
